% This main.m file consists of 8 parts. We use data from 34 experimental
% conditions to predict the 35th experimental condition.
t1=clock;
%%
%---------------------------------------------------------------------%
% Part 1: Data loading and Extract Mass matrix: (estimated time:8.988mins)
%---------------------------------------------------------------------%
load('fem_node_element.mat');load('alldata_Force_Displacement.mat');
full_M_all_lumped=ExtractMass();%lumped mass matrix
% figure;spy(full_M_all_lumped,'k');
t2=clock;
%%
%---------------------------------------------------------------------%
% Part 2: POD (Proper Orthorgonal Decomposition): (estimated time:32.678mins)
%---------------------------------------------------------------------%
r=30;%selected rank of POD truncation
[Uhat,Sig,c1_F_ROM,c1_StateData_displacement_ROM,c2_F_ROM,c2_StateData_displacement_ROM,c3_F_ROM,c3_StateData_displacement_ROM,c4_F_ROM,c4_StateData_displacement_ROM,c5_F_ROM,c5_StateData_displacement_ROM,c6_F_ROM,c6_StateData_displacement_ROM,c7_F_ROM,c7_StateData_displacement_ROM,c8_F_ROM,c8_StateData_displacement_ROM,c9_F_ROM,c9_StateData_displacement_ROM,c10_F_ROM,c10_StateData_displacement_ROM,c11_F_ROM,c11_StateData_displacement_ROM,c12_F_ROM,c12_StateData_displacement_ROM,c13_F_ROM,c13_StateData_displacement_ROM,c14_F_ROM,c14_StateData_displacement_ROM,c15_F_ROM,c15_StateData_displacement_ROM,c16_F_ROM,c16_StateData_displacement_ROM,c17_F_ROM,c17_StateData_displacement_ROM,c18_F_ROM,c18_StateData_displacement_ROM,c19_F_ROM,c19_StateData_displacement_ROM,c20_F_ROM,c20_StateData_displacement_ROM,c21_F_ROM,c21_StateData_displacement_ROM,c22_F_ROM,c22_StateData_displacement_ROM,c23_F_ROM,c23_StateData_displacement_ROM,c24_F_ROM,c24_StateData_displacement_ROM,c25_F_ROM,c25_StateData_displacement_ROM,c26_F_ROM,c26_StateData_displacement_ROM,c27_F_ROM,c27_StateData_displacement_ROM,c28_F_ROM,c28_StateData_displacement_ROM,c29_F_ROM,c29_StateData_displacement_ROM,c30_F_ROM,c30_StateData_displacement_ROM,c31_F_ROM,c31_StateData_displacement_ROM,c32_F_ROM,c32_StateData_displacement_ROM,c33_F_ROM,c33_StateData_displacement_ROM,c34_F_ROM,c34_StateData_displacement_ROM,c35_F_ROM,c35_StateData_displacement_ROM]=POD(r,full_M_all_lumped);
PrepareData(r,c1_F_ROM,c1_StateData_displacement_ROM,c2_F_ROM,c2_StateData_displacement_ROM,c3_F_ROM,c3_StateData_displacement_ROM,c4_F_ROM,c4_StateData_displacement_ROM,c5_F_ROM,c5_StateData_displacement_ROM,c6_F_ROM,c6_StateData_displacement_ROM,c7_F_ROM,c7_StateData_displacement_ROM,c8_F_ROM,c8_StateData_displacement_ROM,c9_F_ROM,c9_StateData_displacement_ROM,c10_F_ROM,c10_StateData_displacement_ROM,c11_F_ROM,c11_StateData_displacement_ROM,c12_F_ROM,c12_StateData_displacement_ROM,c13_F_ROM,c13_StateData_displacement_ROM,c14_F_ROM,c14_StateData_displacement_ROM,c15_F_ROM,c15_StateData_displacement_ROM,c16_F_ROM,c16_StateData_displacement_ROM,c17_F_ROM,c17_StateData_displacement_ROM,c18_F_ROM,c18_StateData_displacement_ROM,c19_F_ROM,c19_StateData_displacement_ROM,c20_F_ROM,c20_StateData_displacement_ROM,c21_F_ROM,c21_StateData_displacement_ROM,c22_F_ROM,c22_StateData_displacement_ROM,c23_F_ROM,c23_StateData_displacement_ROM,c24_F_ROM,c24_StateData_displacement_ROM,c25_F_ROM,c25_StateData_displacement_ROM,c26_F_ROM,c26_StateData_displacement_ROM,c27_F_ROM,c27_StateData_displacement_ROM,c28_F_ROM,c28_StateData_displacement_ROM,c29_F_ROM,c29_StateData_displacement_ROM,c30_F_ROM,c30_StateData_displacement_ROM,c31_F_ROM,c31_StateData_displacement_ROM,c32_F_ROM,c32_StateData_displacement_ROM,c33_F_ROM,c33_StateData_displacement_ROM,c34_F_ROM,c34_StateData_displacement_ROM,c35_F_ROM,c35_StateData_displacement_ROM);
CumForce(r,c1_F_ROM_new,c1_StateData_displacement_ROM_new,c2_F_ROM_new,c2_StateData_displacement_ROM_new,c3_F_ROM_new,c3_StateData_displacement_ROM_new,c4_F_ROM_new,c4_StateData_displacement_ROM_new,c5_F_ROM_new,c5_StateData_displacement_ROM_new,c6_F_ROM_new,c6_StateData_displacement_ROM_new,c7_F_ROM_new,c7_StateData_displacement_ROM_new,c8_F_ROM_new,c8_StateData_displacement_ROM_new,c9_F_ROM_new,c9_StateData_displacement_ROM_new,c10_F_ROM_new,c10_StateData_displacement_ROM_new,c11_F_ROM_new,c11_StateData_displacement_ROM_new,c12_F_ROM_new,c12_StateData_displacement_ROM_new,c13_F_ROM_new,c13_StateData_displacement_ROM_new,c14_F_ROM_new,c14_StateData_displacement_ROM_new,c15_F_ROM_new,c15_StateData_displacement_ROM_new,c16_F_ROM_new,c16_StateData_displacement_ROM_new,c17_F_ROM_new,c17_StateData_displacement_ROM_new,c18_F_ROM_new,c18_StateData_displacement_ROM_new,c19_F_ROM_new,c19_StateData_displacement_ROM_new,c20_F_ROM_new,c20_StateData_displacement_ROM_new,c21_F_ROM_new,c21_StateData_displacement_ROM_new,c22_F_ROM_new,c22_StateData_displacement_ROM_new,c23_F_ROM_new,c23_StateData_displacement_ROM_new,c24_F_ROM_new,c24_StateData_displacement_ROM_new,c25_F_ROM_new,c25_StateData_displacement_ROM_new,c26_F_ROM_new,c26_StateData_displacement_ROM_new,c27_F_ROM_new,c27_StateData_displacement_ROM_new,c28_F_ROM_new,c28_StateData_displacement_ROM_new,c29_F_ROM_new,c29_StateData_displacement_ROM_new,c30_F_ROM_new,c30_StateData_displacement_ROM_new,c31_F_ROM_new,c31_StateData_displacement_ROM_new,c32_F_ROM_new,c32_StateData_displacement_ROM_new,c33_F_ROM_new,c33_StateData_displacement_ROM_new,c34_F_ROM_new,c34_StateData_displacement_ROM_new,c35_F_ROM_new,c35_StateData_displacement_ROM_new);
PiledData(r,c1_F_ROM_new,c1_StateData_displacement_ROM_new,c2_F_ROM_new,c2_StateData_displacement_ROM_new,c3_F_ROM_new,c3_StateData_displacement_ROM_new,c4_F_ROM_new,c4_StateData_displacement_ROM_new,c5_F_ROM_new,c5_StateData_displacement_ROM_new,c6_F_ROM_new,c6_StateData_displacement_ROM_new,c7_F_ROM_new,c7_StateData_displacement_ROM_new,c8_F_ROM_new,c8_StateData_displacement_ROM_new,c9_F_ROM_new,c9_StateData_displacement_ROM_new,c10_F_ROM_new,c10_StateData_displacement_ROM_new,c11_F_ROM_new,c11_StateData_displacement_ROM_new,c12_F_ROM_new,c12_StateData_displacement_ROM_new,c13_F_ROM_new,c13_StateData_displacement_ROM_new,c14_F_ROM_new,c14_StateData_displacement_ROM_new,c15_F_ROM_new,c15_StateData_displacement_ROM_new,c16_F_ROM_new,c16_StateData_displacement_ROM_new,c17_F_ROM_new,c17_StateData_displacement_ROM_new,c18_F_ROM_new,c18_StateData_displacement_ROM_new,c19_F_ROM_new,c19_StateData_displacement_ROM_new,c20_F_ROM_new,c20_StateData_displacement_ROM_new,c21_F_ROM_new,c21_StateData_displacement_ROM_new,c22_F_ROM_new,c22_StateData_displacement_ROM_new,c23_F_ROM_new,c23_StateData_displacement_ROM_new,c24_F_ROM_new,c24_StateData_displacement_ROM_new,c25_F_ROM_new,c25_StateData_displacement_ROM_new,c26_F_ROM_new,c26_StateData_displacement_ROM_new,c27_F_ROM_new,c27_StateData_displacement_ROM_new,c28_F_ROM_new,c28_StateData_displacement_ROM_new,c29_F_ROM_new,c29_StateData_displacement_ROM_new,c30_F_ROM_new,c30_StateData_displacement_ROM_new,c31_F_ROM_new,c31_StateData_displacement_ROM_new,c32_F_ROM_new,c32_StateData_displacement_ROM_new,c33_F_ROM_new,c33_StateData_displacement_ROM_new,c34_F_ROM_new,c34_StateData_displacement_ROM_new,c35_F_ROM_new,c35_StateData_displacement_ROM_new,c1_F_ROM_new_cum2,c2_F_ROM_new_cum2,c3_F_ROM_new_cum2,c4_F_ROM_new_cum2,c5_F_ROM_new_cum2,c6_F_ROM_new_cum2,c7_F_ROM_new_cum2,c8_F_ROM_new_cum2,c9_F_ROM_new_cum2,c10_F_ROM_new_cum2,c11_F_ROM_new_cum2,c12_F_ROM_new_cum2,c13_F_ROM_new_cum2,c14_F_ROM_new_cum2,c15_F_ROM_new_cum2,c16_F_ROM_new_cum2,c17_F_ROM_new_cum2,c18_F_ROM_new_cum2,c19_F_ROM_new_cum2,c20_F_ROM_new_cum2,c21_F_ROM_new_cum2,c22_F_ROM_new_cum2,c23_F_ROM_new_cum2,c24_F_ROM_new_cum2,c25_F_ROM_new_cum2,c26_F_ROM_new_cum2,c27_F_ROM_new_cum2,c28_F_ROM_new_cum2,c29_F_ROM_new_cum2,c30_F_ROM_new_cum2,c31_F_ROM_new_cum2,c32_F_ROM_new_cum2,c33_F_ROM_new_cum2,c34_F_ROM_new_cum2,c35_F_ROM_new_cum2);
t3=clock;
%%
%---------------------------------------------------------------------%
% Part 3: Plot q, F, POD basis: (estimated time:0.3898mins)
%---------------------------------------------------------------------%
%Fig.10 (a)
PlotState(c1_F_ROM_new,c1_StateData_displacement_ROM_new,c2_F_ROM_new,c2_StateData_displacement_ROM_new,c3_F_ROM_new,c3_StateData_displacement_ROM_new,c4_F_ROM_new,c4_StateData_displacement_ROM_new,c5_F_ROM_new,c5_StateData_displacement_ROM_new,c6_F_ROM_new,c6_StateData_displacement_ROM_new,c7_F_ROM_new,c7_StateData_displacement_ROM_new,c8_F_ROM_new,c8_StateData_displacement_ROM_new,c9_F_ROM_new,c9_StateData_displacement_ROM_new,c10_F_ROM_new,c10_StateData_displacement_ROM_new,c11_F_ROM_new,c11_StateData_displacement_ROM_new,c12_F_ROM_new,c12_StateData_displacement_ROM_new,c13_F_ROM_new,c13_StateData_displacement_ROM_new,c14_F_ROM_new,c14_StateData_displacement_ROM_new,c15_F_ROM_new,c15_StateData_displacement_ROM_new,c16_F_ROM_new,c16_StateData_displacement_ROM_new,c17_F_ROM_new,c17_StateData_displacement_ROM_new,c18_F_ROM_new,c18_StateData_displacement_ROM_new,c19_F_ROM_new,c19_StateData_displacement_ROM_new,c20_F_ROM_new,c20_StateData_displacement_ROM_new,c21_F_ROM_new,c21_StateData_displacement_ROM_new,c22_F_ROM_new,c22_StateData_displacement_ROM_new,c23_F_ROM_new,c23_StateData_displacement_ROM_new,c24_F_ROM_new,c24_StateData_displacement_ROM_new,c25_F_ROM_new,c25_StateData_displacement_ROM_new,c26_F_ROM_new,c26_StateData_displacement_ROM_new,c27_F_ROM_new,c27_StateData_displacement_ROM_new,c28_F_ROM_new,c28_StateData_displacement_ROM_new,c29_F_ROM_new,c29_StateData_displacement_ROM_new,c30_F_ROM_new,c30_StateData_displacement_ROM_new,c31_F_ROM_new,c31_StateData_displacement_ROM_new,c32_F_ROM_new,c32_StateData_displacement_ROM_new,c33_F_ROM_new,c33_StateData_displacement_ROM_new,c34_F_ROM_new,c34_StateData_displacement_ROM_new,c35_F_ROM_new,c35_StateData_displacement_ROM_new);
%Fig.10 (b)
PlotForce(c1_F_ROM_new_cum2,c2_F_ROM_new_cum2,c3_F_ROM_new_cum2,c4_F_ROM_new_cum2,c5_F_ROM_new_cum2,c6_F_ROM_new_cum2,c7_F_ROM_new_cum2,c8_F_ROM_new_cum2,c9_F_ROM_new_cum2,c10_F_ROM_new_cum2,c11_F_ROM_new_cum2,c12_F_ROM_new_cum2,c13_F_ROM_new_cum2,c14_F_ROM_new_cum2,c15_F_ROM_new_cum2,c16_F_ROM_new_cum2,c17_F_ROM_new_cum2,c18_F_ROM_new_cum2,c19_F_ROM_new_cum2,c20_F_ROM_new_cum2,c21_F_ROM_new_cum2,c22_F_ROM_new_cum2,c23_F_ROM_new_cum2,c24_F_ROM_new_cum2,c25_F_ROM_new_cum2,c26_F_ROM_new_cum2,c27_F_ROM_new_cum2,c28_F_ROM_new_cum2,c29_F_ROM_new_cum2,c30_F_ROM_new_cum2,c31_F_ROM_new_cum2,c32_F_ROM_new_cum2,c33_F_ROM_new_cum2,c34_F_ROM_new_cum2,c35_F_ROM_new_cum2);
%Fig.9 (1)
index_PODbasis = 1; PlotPODbasis(Uhat(:,index_PODbasis)'); %index_PODbasis can be set to be 1~30, as which POD basis you want to check
t4=clock;
%%
%---------------------------------------------------------------------%
% Part 4: Prepare data matrix for mFPCA in R; Load mFPCA basis which has
% been calculated in R: (estimated time:0.0121mins)
%---------------------------------------------------------------------%
[displacement_allcondition,force_allcondition]=PrepareMFPCAdata(c1_F_ROM_new_cum2_piled,c1_StateData_displacement_ROM_new_piled,c2_F_ROM_new_cum2_piled,c2_StateData_displacement_ROM_new_piled,c3_F_ROM_new_cum2_piled,c3_StateData_displacement_ROM_new_piled,c4_F_ROM_new_cum2_piled,c4_StateData_displacement_ROM_new_piled,c5_F_ROM_new_cum2_piled,c5_StateData_displacement_ROM_new_piled,c6_F_ROM_new_cum2_piled,c6_StateData_displacement_ROM_new_piled,c7_F_ROM_new_cum2_piled,c7_StateData_displacement_ROM_new_piled,c8_F_ROM_new_cum2_piled,c8_StateData_displacement_ROM_new_piled,c9_F_ROM_new_cum2_piled,c9_StateData_displacement_ROM_new_piled,c10_F_ROM_new_cum2_piled,c10_StateData_displacement_ROM_new_piled,c11_F_ROM_new_cum2_piled,c11_StateData_displacement_ROM_new_piled,c12_F_ROM_new_cum2_piled,c12_StateData_displacement_ROM_new_piled,c13_F_ROM_new_cum2_piled,c13_StateData_displacement_ROM_new_piled,c14_F_ROM_new_cum2_piled,c14_StateData_displacement_ROM_new_piled,c15_F_ROM_new_cum2_piled,c15_StateData_displacement_ROM_new_piled,c16_F_ROM_new_cum2_piled,c16_StateData_displacement_ROM_new_piled,c17_F_ROM_new_cum2_piled,c17_StateData_displacement_ROM_new_piled,c18_F_ROM_new_cum2_piled,c18_StateData_displacement_ROM_new_piled,c19_F_ROM_new_cum2_piled,c19_StateData_displacement_ROM_new_piled,c20_F_ROM_new_cum2_piled,c20_StateData_displacement_ROM_new_piled,c21_F_ROM_new_cum2_piled,c21_StateData_displacement_ROM_new_piled,c22_F_ROM_new_cum2_piled,c22_StateData_displacement_ROM_new_piled,c23_F_ROM_new_cum2_piled,c23_StateData_displacement_ROM_new_piled,c24_F_ROM_new_cum2_piled,c24_StateData_displacement_ROM_new_piled,c25_F_ROM_new_cum2_piled,c25_StateData_displacement_ROM_new_piled,c26_F_ROM_new_cum2_piled,c26_StateData_displacement_ROM_new_piled,c27_F_ROM_new_cum2_piled,c27_StateData_displacement_ROM_new_piled,c28_F_ROM_new_cum2_piled,c28_StateData_displacement_ROM_new_piled,c29_F_ROM_new_cum2_piled,c29_StateData_displacement_ROM_new_piled,c30_F_ROM_new_cum2_piled,c30_StateData_displacement_ROM_new_piled,c31_F_ROM_new_cum2_piled,c31_StateData_displacement_ROM_new_piled,c32_F_ROM_new_cum2_piled,c32_StateData_displacement_ROM_new_piled,c33_F_ROM_new_cum2_piled,c33_StateData_displacement_ROM_new_piled,c34_F_ROM_new_cum2_piled,c34_StateData_displacement_ROM_new_piled,c35_F_ROM_new_cum2_piled,c35_StateData_displacement_ROM_new_piled);
load('loworder_force_phi_POD30.mat');load('loworder_force_mean_POD30.mat');load('loworder_displacement_phi_POD30.mat');load('loworder_displacement_mean_POD30.mat');
t5=clock;
%%
%---------------------------------------------------------------------%
% Part 5: Multivariate Gaussian Process Regression: (estimated time:0.89mins)
%---------------------------------------------------------------------%
[predict_FPCA_force_score,predict_FPCA_force_covariance,displacement_allcondition_mean,force_allcondition_mean,displacement_allcondition_centered,force_allcondition_centered,FPCA_dis_mean,FPCA_dis,FPCA_force_mean,FPCA_force]=mGPR(displacement_allcondition,force_allcondition,displacementmean,displacementFPCAbasis,forcemean,forceFPCAbasis);
t6=clock;
%%
%---------------------------------------------------------------------%
% Part 6: Multivariate Linear Regression: (estimated time:0.00015mins)
%---------------------------------------------------------------------%
[B_estimated,covariance_LinearReg]=mLR(FPCA_force,FPCA_dis);
t7=clock;
%%
%---------------------------------------------------------------------%
% Part 7: Prediction: (estimated time:1.38mins)
%---------------------------------------------------------------------%
[predict_FPCA_displacement_score,full_predict_displacement_filed,covariance_FPCA_displacement,full_predict_displacement_POD,covariance_POD_displacement]=Prediction(r,B_estimated,covariance_LinearReg,predict_FPCA_force_score,predict_FPCA_force_covariance,displacement_allcondition_mean,force_allcondition_mean,displacement_allcondition_centered,force_allcondition_centered,FPCA_dis_mean,FPCA_dis,FPCA_force_mean,FPCA_force,displacement_allcondition,force_allcondition,displacementmean,displacementFPCAbasis,forcemean,forceFPCAbasis);
[Mean_predict,Var_predict] = predict_displacement_vector_plot(30,400,20,displacementFPCAbasis,covariance_FPCA_displacement,full_predict_displacement_POD,Uhat);%calculated total displacement
t8=clock;
%%
%---------------------------------------------------------------------%
% Part 8: Visualization: (estimated time:1.552mins)
%---------------------------------------------------------------------%
PlotMSE(Uhat,full_predict_displacement_POD,c35_StateData_displacement);%Fig.17: line #35
PlotNodalDeformation(4999,r,Uhat,full_predict_displacement_POD,c35_StateData_displacement,displacementFPCAbasis,covariance_FPCA_displacement);%Fig.11 the first subplot
PlotDisplacementXpre(400,Uhat,full_predict_displacement_POD);%Fig.13 top
PlotDisplacementXactual(370,c35_StateData_displacement);%Fig.13 middle
PlotXstandarddeviation(Uhat,covariance_POD_displacement);%Fig.13 bottom
t9=clock;



