function [displacement_allcondition,force_allcondition]=PrepareMFPCAdata(c1_F_ROM_new_cum2_piled,c1_StateData_displacement_ROM_new_piled,c2_F_ROM_new_cum2_piled,c2_StateData_displacement_ROM_new_piled,c3_F_ROM_new_cum2_piled,c3_StateData_displacement_ROM_new_piled,c4_F_ROM_new_cum2_piled,c4_StateData_displacement_ROM_new_piled,c5_F_ROM_new_cum2_piled,c5_StateData_displacement_ROM_new_piled,c6_F_ROM_new_cum2_piled,c6_StateData_displacement_ROM_new_piled,c7_F_ROM_new_cum2_piled,c7_StateData_displacement_ROM_new_piled,c8_F_ROM_new_cum2_piled,c8_StateData_displacement_ROM_new_piled,c9_F_ROM_new_cum2_piled,c9_StateData_displacement_ROM_new_piled,c10_F_ROM_new_cum2_piled,c10_StateData_displacement_ROM_new_piled,c11_F_ROM_new_cum2_piled,c11_StateData_displacement_ROM_new_piled,c12_F_ROM_new_cum2_piled,c12_StateData_displacement_ROM_new_piled,c13_F_ROM_new_cum2_piled,c13_StateData_displacement_ROM_new_piled,c14_F_ROM_new_cum2_piled,c14_StateData_displacement_ROM_new_piled,c15_F_ROM_new_cum2_piled,c15_StateData_displacement_ROM_new_piled,c16_F_ROM_new_cum2_piled,c16_StateData_displacement_ROM_new_piled,c17_F_ROM_new_cum2_piled,c17_StateData_displacement_ROM_new_piled,c18_F_ROM_new_cum2_piled,c18_StateData_displacement_ROM_new_piled,c19_F_ROM_new_cum2_piled,c19_StateData_displacement_ROM_new_piled,c20_F_ROM_new_cum2_piled,c20_StateData_displacement_ROM_new_piled,c21_F_ROM_new_cum2_piled,c21_StateData_displacement_ROM_new_piled,c22_F_ROM_new_cum2_piled,c22_StateData_displacement_ROM_new_piled,c23_F_ROM_new_cum2_piled,c23_StateData_displacement_ROM_new_piled,c24_F_ROM_new_cum2_piled,c24_StateData_displacement_ROM_new_piled,c25_F_ROM_new_cum2_piled,c25_StateData_displacement_ROM_new_piled,c26_F_ROM_new_cum2_piled,c26_StateData_displacement_ROM_new_piled,c27_F_ROM_new_cum2_piled,c27_StateData_displacement_ROM_new_piled,c28_F_ROM_new_cum2_piled,c28_StateData_displacement_ROM_new_piled,c29_F_ROM_new_cum2_piled,c29_StateData_displacement_ROM_new_piled,c30_F_ROM_new_cum2_piled,c30_StateData_displacement_ROM_new_piled,c31_F_ROM_new_cum2_piled,c31_StateData_displacement_ROM_new_piled,c32_F_ROM_new_cum2_piled,c32_StateData_displacement_ROM_new_piled,c33_F_ROM_new_cum2_piled,c33_StateData_displacement_ROM_new_piled,c34_F_ROM_new_cum2_piled,c34_StateData_displacement_ROM_new_piled,c35_F_ROM_new_cum2_piled,c35_StateData_displacement_ROM_new_piled)
displacement_allcondition = [];
for jk = 1:35
    dataset = [];
    dataset_name=strcat('c',num2str(jk),'_StateData_displacement_ROM_new_piled');
    dataset = eval(dataset_name);
    displacement_allcondition = [displacement_allcondition;dataset];
end

force_allcondition = [];
for jk = 1:35
    dataset = [];
    dataset_name=strcat('c',num2str(jk),'_F_ROM_new_cum2_piled');
    dataset = eval(dataset_name);
    force_allcondition = [force_allcondition;dataset];
end